name: Fetch News

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create simple JSON
        run: |
          echo '[{"title":"Test News Working","link":"https://google.com"}]' > data.json

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "update data" || echo "no changes"
          git push
